In [6]:
import numpy as np
import tensorflow as tf

softmax(x-a)=softmax(a), using it can avoid exp(x) become inf

And this softmax function parameter x can be matrix and vecter. If x is a matrix, this function computer the softmax prediction for each row.

In [4]:
def softmax(X):
    
    #get the vecture shape
    X_shape = X.shape;
    
    #transform X
    X = X.T
    
    Max = np.max(X, axis=0)
    
    #reduce X, avoid exp(X) become inf
    X = X - Max
    
    #y=softmax(x)
    Y = np.exp(X)/np.sum(np.exp(X), axis=0)
    
    Y=Y.T
    
    return Y

In [20]:
x = np.array([[1,2,3],[2,4,3]], dtype=np.float32)

In [21]:
y = softmax(x)
print(y)

[[ 0.09003057  0.24472848  0.66524094]
 [ 0.09003057  0.66524088  0.24472846]]


In [22]:
y = tf.nn.softmax(x)
with tf.Session() as sess:
    print(sess.run(y))
    sess.close()

[[ 0.09003057  0.24472848  0.66524094]
 [ 0.09003057  0.66524088  0.24472845]]
